"""changed 'name' to 'full_name' in Character table

Revision ID: 0967bf236dcc
Revises: fcd6862b5755
Create Date: 2022-05-24 11:47:31.688357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0967bf236dcc'
down_revision = 'fcd6862b5755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('character', 'name', new_column_name='full_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('character', 'full_name', new_column_name='name')

    # ### end Alembic commands ###
