"""added World table

Revision ID: 0bc631afe888
Revises: e4bdef23b10f
Create Date: 2022-03-31 11:24:38.606033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc631afe888'
down_revision = 'e4bdef23b10f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('world',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('world', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_world_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_world_name'))

    op.drop_table('world')
    # ### end Alembic commands ###
