"""changed 'name' to 'full_name' in Character table, ATTEMPT 3

Revision ID: 67e8627dc87b
Revises: 079e32136b41
Create Date: 2022-05-25 11:17:21.554015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e8627dc87b'
down_revision = '079e32136b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('character', 'name', new_column_name='full_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('character', 'full_name', new_column_name='name')

    # ### end Alembic commands ###
