"""deleted incorrect Prompt column

Revision ID: 6928289a2eb6
Revises: bf11a1805b66
Create Date: 2022-04-10 20:32:06.922969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6928289a2eb6'
down_revision = 'bf11a1805b66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.drop_column('participants')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participants', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
