"""changed 'prompt' to 'text' in Prompt table

Revision ID: 8fcbf978bb86
Revises: e5e0954cd59a
Create Date: 2022-05-09 22:34:05.372049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fcbf978bb86'
down_revision = 'e5e0954cd59a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.String(), nullable=True))
        batch_op.drop_column('prompt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('text')

    # ### end Alembic commands ###
