"""changed 'prompt' to 'text' in Prompt table, attempt 3

Revision ID: 9b3ae048b0e3
Revises: fc75a6ccfb21
Create Date: 2022-05-10 11:10:49.662398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3ae048b0e3'
down_revision = 'fc75a6ccfb21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.alter_column('prompt', 'prompt', new_column_name='text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.alter_column('prompt', 'text', new_column_name='prompt')

    # ### end Alembic commands ###
