"""added 'snippet' column to Story table

Revision ID: ae1121a0c83f
Revises: eff7cfe905aa
Create Date: 2022-07-07 21:49:08.228819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae1121a0c83f'
down_revision = 'eff7cfe905aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snippet', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.drop_column('snippet')

    # ### end Alembic commands ###
