"""added relatives_character relationship table

Revision ID: c7c25cbde836
Revises: 06d542d255e9
Create Date: 2022-04-27 11:16:05.727772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c25cbde836'
down_revision = '06d542d255e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relatives_character',
    sa.Column('relative_a', sa.Integer(), nullable=True),
    sa.Column('relative_b', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['relative_a'], ['character.id'], ),
    sa.ForeignKeyConstraint(['relative_b'], ['character.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relatives_character')
    # ### end Alembic commands ###
