"""added prompt_id column to Story table

Revision ID: e5e0954cd59a
Revises: c7c25cbde836
Create Date: 2022-05-09 21:36:19.375415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5e0954cd59a'
down_revision = 'c7c25cbde836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'prompt', ['prompt_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('prompt_id')

    # ### end Alembic commands ###
